# Generated by Django 5.0.7 on 2025-10-28 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RootPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='İl')),
                ('district', models.CharField(max_length=64, verbose_name='İlçe')),
                ('place_type', models.CharField(choices=[('klinik', 'Klinik'), ('eczane', 'Eczane'), ('ciftlik', 'Çiftlik'), ('diger', 'Diğer')], max_length=16, verbose_name='Ziyaret Türü')),
                ('place_name', models.CharField(max_length=128, verbose_name='Yer Adı')),
                ('visit_purpose', models.CharField(max_length=200, verbose_name='Ziyaret Amacı')),
                ('visit_date', models.DateField(verbose_name='Tarih')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rootplans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ziyaret',
                'verbose_name_plural': 'Ziyaretler',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
